### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by Anmol567** [Shreyz-max/Video-Captioning#1]
The model is not giving the same results when tested on the same videos you have uploaded .

**Comment by Shreyz-max** [comment]
Hi Anmol,
Thank you for going through the project.
Models may give varying results. Some captions might be good others might
not be. You can try the pretrained model with the weights I have uploaded
on GitHub and run through that. If even then you find the results different
you should definitely reach out to me again.

If you are training on your own maybe I could go through the code and check
out where the problem is.
Thank you.

Regards,
Shreya
